import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import Navbar from '@/components/Navbar';
import FormStart from '@/components/FormStart';
import { useSelector } from 'react-redux';
import { RootState } from '@/redux/store';
import Result from '@/components/Result';
import { useSession } from 'next-auth/react';

export default function Home() {
  const { data: session } = useSession();
  const { isStart, isOver } = useSelector((state: RootState) => state.game);

  return (
    <>
      <Head>
        <title>Quiz App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <meta name='theme-color' content='#317EFB' />
        <link rel='apple-touch-icon' href='/apple-icon.png'></link>
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <main className={styles.main}>
        {session && session.user ? (
          <>
            {!isStart && !isOver && <FormStart />}
            {isOver && <Result />}
          </>
        ) : (
          <>
            <h1>Welcome to the quiz app</h1>
            <h2>Wanna start? Login first</h2>
          </>
        )}
      </main>
    </>
  );
}
